import type { MarketCommunity } from "./types";

export const hendersonCommunities: MarketCommunity[] = [
  {
    slug: "lake-las-vegas",
    name: "Lake Las Vegas",
    tagline: "Resort living on a 320-acre private lake",
    priceRange: "$600K – $5M+",
    description: `Lake Las Vegas is Henderson's most distinctive address — a 3,592-acre master-planned resort community built around a 320-acre private lake. Residents enjoy lakefront dining, a marina, golf, tennis, and a walkable village. Homes range from attached townhomes near the water to multi-million-dollar custom estates on hillside lots with panoramic lake and mountain views.`,
    highlights: [
      "Lakefront estates & villas",
      "Reflection Bay Golf Club",
      "The Village at Lake Las Vegas",
      "Marina & water sports",
      "On-site resort hotels",
      "Guard-gated enclaves",
    ],
    bestFor: [
      "Luxury buyers",
      "Resort lifestyle",
      "Vacation & second home",
      "Waterfront living",
    ],
    address: "Lake Las Vegas Pkwy",
    zip: "89011",
  },
  {
    slug: "macdonald-ranch",
    name: "MacDonald Ranch",
    tagline: "Master-planned luxury in east Henderson",
    priceRange: "$550K – $1.8M",
    description: `MacDonald Ranch is one of Henderson's premier master-planned communities, known for well-maintained streetscapes, guard-gated neighborhoods, and top-performing schools. Located in the heart of east Henderson, it offers convenient access to the 215 Beltway, Green Valley Pkwy amenities, and the Desert Willow Golf Resort. Homes feature desert-contemporary architecture, large lots, and dramatic mountain views.`,
    highlights: [
      "Desert Willow Golf Resort",
      "Guard-gated options",
      "Top-rated CCSD schools",
      "Mountain & valley views",
      "Luxury custom homes",
      "Close to 215 access",
    ],
    bestFor: [
      "Families",
      "Golf enthusiasts",
      "Luxury move-up buyers",
      "California equity buyers",
    ],
    address: "MacDonald Ranch Dr",
    zip: "89012",
  },
  {
    slug: "macdonald-highlands",
    name: "MacDonald Highlands",
    tagline: "Henderson's most prestigious guard-gated luxury community",
    priceRange: "$1.2M – $10M+",
    description: `MacDonald Highlands is Henderson's crown-jewel luxury address — a guard-gated hillside community overlooking the Las Vegas Valley with custom estates, dramatic Strip and mountain views, and the DragonRidge Country Club. Homes range from refined luxury residences to multi-million-dollar architectural estates on generous hillside lots. Dr. Jan Duffy specializes in private showings and discreet representation for buyers and sellers in this premier enclave.`,
    highlights: [
      "Guard-gated luxury enclave",
      "DragonRidge Country Club",
      "Custom architectural estates",
      "Panoramic Strip & valley views",
      "Hillside lots with privacy",
      "Private showings available",
    ],
    bestFor: [
      "Luxury estate buyers",
      "Custom build purchasers",
      "Privacy seekers",
      "Golf & resort lifestyle buyers",
    ],
    address: "MacDonald Highlands Dr",
    zip: "89052",
  },
  {
    slug: "green-valley-ranch",
    name: "Green Valley Ranch",
    tagline: "Established community with everything nearby",
    priceRange: "$400K – $1.2M",
    description: `Green Valley Ranch is Henderson's most walkable and amenity-rich neighborhood — home to The District shopping and dining, the award-winning Green Valley Ranch Resort, and some of the highest-rated elementary schools in Clark County. The community blends established neighborhoods with newer builds, making it an ideal choice for buyers who want move-in-ready homes with a true neighborhood feel.`,
    highlights: [
      "The District shopping & dining",
      "Green Valley Ranch Resort",
      "Award-winning schools",
      "Extensive trail system",
      "Variety of price points",
      "Easy freeway access",
    ],
    bestFor: [
      "First-time buyers",
      "Families",
      "Move-up buyers",
      "Retirees who want walkability",
    ],
    address: "Green Valley Pkwy",
    zip: "89014",
  },
  {
    slug: "seven-hills",
    name: "Seven Hills",
    tagline: "Elevated living with panoramic valley views",
    priceRange: "$500K – $2.5M",
    description: `Seven Hills is built on the elevated terrain of southeast Henderson, delivering some of the most dramatic views in the Las Vegas Valley — city lights, the Strip, Red Rock Canyon, and multiple mountain ranges. The community features the Rio Secco Golf Club, gated enclaves, and custom estate homes on generous lots. It attracts buyers who prioritize privacy, prestige, and scenery.`,
    highlights: [
      "Rio Secco Golf Club",
      "Strip & mountain panoramas",
      "Custom estate lots",
      "Guard-gated villages",
      "Low density",
      "Short drive to Henderson Executive Airport",
    ],
    bestFor: [
      "Luxury buyers",
      "Golf buyers",
      "Privacy seekers",
      "WA & CA equity buyers",
    ],
    address: "Seven Hills Dr",
    zip: "89052",
  },
  {
    slug: "anthem",
    name: "Anthem",
    tagline: "Henderson's iconic resort-style community",
    priceRange: "$450K – $1.5M",
    description: `Anthem spans two distinct districts — Anthem Country Club (guard-gated, private golf, resort amenities) and Anthem Highlands (family-focused with community center, pools, and parks). Del Webb at Sun City Anthem serves the 55+ buyer with world-class active adult amenities. Together, Anthem offers something for nearly every buyer profile, with some of Henderson's best views and the lowest HOA-to-amenity ratios in the market.`,
    highlights: [
      "Anthem Country Club (private golf)",
      "Sun City Anthem 55+ options",
      "Community Center & pools",
      "Hiking at Sloan Canyon",
      "Mountain & valley views",
      "Multiple price tiers",
    ],
    bestFor: [
      "55+ buyers",
      "Golf buyers",
      "Families",
      "Active lifestyle buyers",
    ],
    address: "Anthem Pkwy",
    zip: "89052",
  },
  {
    slug: "inspirada",
    name: "Inspirada",
    tagline: "West Henderson's newest master plan",
    priceRange: "$450K – $900K",
    description: `Inspirada is west Henderson's most vibrant new community — a walkable, park-dense master plan where residents live blocks from resort-style pools, dog parks, and miles of trails. Top builders including Toll Brothers, Woodside, and Taylor Morrison are still delivering new inventory, meaning buyers can customize finishes and lock in builder incentives. The community is attracting young families and California equity buyers priced out of Summerlin.`,
    highlights: [
      "New construction available",
      "Multiple community pools",
      "Walkable park system",
      "Top builders (Toll, Woodside)",
      "West Henderson location",
      "Strong resale appreciation",
    ],
    bestFor: [
      "New construction buyers",
      "Families",
      "California equity buyers",
      "First-time luxury buyers",
    ],
    address: "Inspirada Blvd",
    zip: "89044",
  },
];

export function getHendersonCommunity(
  slug: string,
): MarketCommunity | undefined {
  return hendersonCommunities.find((c) => c.slug === slug);
}
