import type { MarketCommunity } from "./types";

export const lasVegasCommunities: MarketCommunity[] = [
  {
    slug: "centennial-hills",
    name: "Centennial Hills",
    tagline: "Northwest master-planned living with easy mountain access",
    priceRange: "$450K – $1.2M",
    description: `Centennial Hills is one of northwest Las Vegas's most established master-planned corridors, anchored by the Centennial Hills Town Center and offering a mix of single-family homes, gated communities, and new construction. The area sits at the base of the Spring Mountains, with quick access to hiking, biking, and outdoor recreation. Top-performing schools, proximity to US-95, and a strong community infrastructure make it a perennial favorite for move-up buyers and relocating families.`,
    highlights: [
      "Centennial Hills Town Center",
      "US-95 corridor access",
      "Gated community options",
      "Top CCSD schools nearby",
      "Mountain recreation access",
      "Mix of resale & new construction",
    ],
    bestFor: ["Families", "Move-up buyers", "CA equity buyers", "Outdoor lifestyle buyers"],
    address: "Centennial Pkwy",
    zip: "89149",
  },
  {
    slug: "spring-valley",
    name: "Spring Valley",
    tagline: "Established southwest Las Vegas with unbeatable location",
    priceRange: "$350K – $900K",
    description: `Spring Valley is one of Las Vegas's most established and densely populated communities, offering exceptional proximity to the Strip, the airport, and the Las Vegas Medical District. The area features a wide variety of housing — from entry-level single-family homes to executive-level gated neighborhoods. Its central location, mature trees, and access to major employers make it a top choice for professionals, investors, and buyers seeking strong rental income potential.`,
    highlights: [
      "Minutes from the Strip",
      "Proximity to Medical District",
      "Wide price range",
      "Gated community options",
      "Strong rental demand",
      "Easy I-15 & 215 access",
    ],
    bestFor: [
      "Investors",
      "First-time buyers",
      "Medical professionals",
      "Buyers wanting central location",
    ],
    address: "Spring Valley",
    zip: "89147",
  },
  {
    slug: "rhodes-ranch",
    name: "Rhodes Ranch",
    tagline: "Guard-gated golf community in southwest Las Vegas",
    priceRange: "$400K – $850K",
    description: `Rhodes Ranch is a guard-gated, master-planned community built around the Rhodes Ranch Golf Club in southwest Las Vegas. The community offers resort-style amenities including pools, a fitness center, and a clubhouse, with homes ranging from attached townhomes to single-family estates surrounding the golf course. Its southwest location provides easy access to the 215 Beltway and is positioned between Summerlin and Henderson — ideal for buyers who want the guard-gate lifestyle without the premium price tag of luxury enclaves.`,
    highlights: [
      "Rhodes Ranch Golf Club",
      "Guard-gated 24/7",
      "Resort pools & clubhouse",
      "Townhomes to single-family",
      "215 Beltway access",
      "Value-priced guard-gate",
    ],
    bestFor: ["Golf buyers", "First-time luxury buyers", "Move-up buyers", "Investors"],
    address: "Rhodes Ranch Pkwy",
    zip: "89148",
  },
  {
    slug: "silverstone-ranch",
    name: "Silverstone Ranch",
    tagline: "Northwest gated community with mountain backdrop",
    priceRange: "$500K – $1.1M",
    description: `Silverstone Ranch is a gated community in northwest Las Vegas that delivers impressive mountain and desert views without the Summerlin price premium. Homes are well-maintained single-family residences ranging from 2,000 to over 4,000 square feet, many with private pools and upgraded finishes. The community is positioned adjacent to Lone Mountain Regional Park, giving residents immediate trail access. Strong resale values and a loyal buyer base make it one of northwest Las Vegas's most consistent performers.`,
    highlights: [
      "Gated community",
      "Lone Mountain Regional Park adjacent",
      "Mountain & desert views",
      "Private pools standard",
      "Northwest Las Vegas location",
      "Strong resale history",
    ],
    bestFor: ["Move-up buyers", "Families", "Outdoor lifestyle buyers", "CA equity buyers"],
    address: "Silverstone Ranch Dr",
    zip: "89131",
  },
  {
    slug: "lone-mountain",
    name: "Lone Mountain",
    tagline: "Spacious lots and mountain views in northwest Las Vegas",
    priceRange: "$400K – $950K",
    description: `Lone Mountain takes its name from the 3,596-foot peak that serves as its backdrop — giving residents dramatic views that belie the area's mid-range price point. The community is characterized by larger lots than typical Las Vegas neighborhoods, mature landscaping, and a mix of single-story and two-story homes. Lone Mountain Regional Park provides direct trail access for hiking and cycling. The area sits between Centennial Hills and Summerlin, capturing the best of both locations at a price that leaves equity on the table.`,
    highlights: [
      "Lone Mountain Regional Park",
      "Larger-than-average lots",
      "Mountain & valley views",
      "Mix of home sizes",
      "Trail system access",
      "Between Centennial Hills & Summerlin",
    ],
    bestFor: ["Families", "Outdoor lifestyle buyers", "Value-focused buyers", "Move-up buyers"],
    address: "Lone Mountain Rd",
    zip: "89129",
  },
  {
    slug: "arts-district",
    name: "Arts District",
    tagline: "Downtown Las Vegas walkable urban living",
    priceRange: "$300K – $700K",
    description: `The Arts District — centered around Main Street and Charleston Boulevard — is Las Vegas's most walkable urban neighborhood and the city's creative hub. Loft condos, townhomes, and renovated mid-century homes sit alongside galleries, breweries, coffee shops, and independent restaurants. First Friday draws thousands monthly. The area is attracting a growing wave of young professionals, remote workers, and investors who see the long-term appreciation potential of downtown Las Vegas's revitalization. Strong short-term rental demand for Airbnb-permitted units.`,
    highlights: [
      "Walkable urban neighborhood",
      "First Friday arts district",
      "Lofts & townhomes",
      "Strong short-term rental demand",
      "Renovation & appreciation upside",
      "Close to Medical District & UNLV",
    ],
    bestFor: [
      "Investors",
      "Young professionals",
      "Urban lifestyle buyers",
      "Short-term rental investors",
    ],
    address: "S Main St",
    zip: "89101",
  },
];

export function getLasVegasCommunity(slug: string): MarketCommunity | undefined {
  return lasVegasCommunities.find((c) => c.slug === slug);
}
