import type { MarketCommunity } from "./types";

export const summerlinCommunities: MarketCommunity[] = [
  {
    slug: "the-ridges",
    name: "The Ridges",
    tagline: "Summerlin's most prestigious guard-gated estate community",
    priceRange: "$1.5M – $10M+",
    description: `The Ridges is Summerlin's crown jewel — a guard-gated enclave of custom and semi-custom estates set against the dramatic backdrop of Red Rock Canyon. Homes sit on generous lots with panoramic views of the Las Vegas Strip, the valley, and multiple mountain ranges. Bear's Best Golf Club anchors the community. Architecture ranges from contemporary desert-modern to Mediterranean, with most homes exceeding 4,000 square feet. Resale inventory is limited and moves fast — this is one of the most sought-after addresses in all of Nevada.`,
    highlights: [
      "Bear's Best Golf Club",
      "Guard-gated 24/7",
      "Custom & semi-custom estates",
      "Strip & Red Rock views",
      "Luxury finishes standard",
      "Close to Downtown Summerlin",
    ],
    bestFor: ["Luxury buyers", "Privacy seekers", "Golf buyers", "CA & WA equity buyers"],
    address: "The Ridges",
    zip: "89135",
  },
  {
    slug: "the-summit",
    name: "The Summit Club",
    tagline: "Ultra-exclusive private club with Tom Fazio golf",
    priceRange: "$3M – $20M+",
    description: `The Summit Club is Las Vegas's most exclusive address — a private, member-only club community developed in partnership with Discovery Land Company. Perched above the valley at 3,000+ feet elevation, it features a Tom Fazio-designed golf course, world-class clubhouse, spa, beach club, and farm-to-table dining. Homesites range from estate lots to custom compounds. Access requires both membership and property ownership. This is where the valley's ultra-high-net-worth residents choose to call home.`,
    highlights: [
      "Tom Fazio private golf",
      "Discovery Land Company",
      "Member-only access",
      "Elevated canyon views",
      "World-class club amenities",
      "Limited inventory",
    ],
    bestFor: [
      "Ultra-luxury buyers",
      "Family office clients",
      "Second home / retreat",
      "Privacy + prestige seekers",
    ],
    address: "The Summit Club Dr",
    zip: "89135",
  },
  {
    slug: "red-rock-country-club",
    name: "Red Rock Country Club",
    tagline: "Private golf and resort living at the foot of Red Rock Canyon",
    priceRange: "$800K – $5M",
    description: `Red Rock Country Club delivers luxury resort living in a private, guard-gated setting directly adjacent to Red Rock Canyon National Conservation Area. Two championship golf courses — the Arroyo and the Mountain — wind through the community. Homes range from attached patio homes and villas to custom estate lots with unobstructed canyon views. The clubhouse features fine dining, tennis, a fitness center, and resort-style pools. It's one of the best value-per-square-foot luxury addresses in Summerlin.`,
    highlights: [
      "Two championship golf courses",
      "Guard-gated community",
      "Red Rock Canyon views",
      "Resort clubhouse & pools",
      "Patio homes to custom estates",
      "Adjacent to 197,000-acre preserve",
    ],
    bestFor: ["Golf buyers", "Luxury move-up buyers", "CA equity buyers", "Active lifestyle buyers"],
    address: "Red Rock Country Club Dr",
    zip: "89135",
  },
  {
    slug: "stonebridge",
    name: "Stonebridge",
    tagline: "Summerlin West's premier new master-planned community",
    priceRange: "$600K – $1.5M",
    description: `Stonebridge is one of Summerlin West's newest and most desirable master-planned communities, offering new construction from top builders including Toll Brothers, Woodside Homes, and Taylor Morrison. Elevated terrain delivers exceptional Strip, valley, and mountain views from most homesites. The community features resort-style pools, parks, and trail connections to the greater Summerlin trail network. Heritage at Stonebridge — the Del Webb 55+ component — occupies the southern portion. Strong appreciation trajectory as remaining phases build out.`,
    highlights: [
      "New construction available",
      "Toll Brothers & Taylor Morrison",
      "Elevated Strip & valley views",
      "Resort pools & parks",
      "Heritage 55+ adjacent",
      "Summerlin trail access",
    ],
    bestFor: [
      "New construction buyers",
      "Move-up buyers",
      "CA equity buyers",
      "55+ buyers (Heritage component)",
    ],
    address: "Stonebridge Dr",
    zip: "89138",
  },
  {
    slug: "heritage-stonebridge",
    name: "Heritage at Stonebridge",
    tagline: "Del Webb's newest Las Vegas 55+ community",
    priceRange: "$500K – $950K",
    description: `Heritage at Stonebridge is Del Webb's newest active adult community in Las Vegas — and its most dramatically sited. Built into the elevated western edge of Summerlin, homes here deliver some of the most spectacular Strip and valley views of any 55+ community in Nevada. The amenity center features resort pools, pickleball, bocce, a fitness center, and a full calendar of social programming. Single-story floor plans from 1,500 to 2,800 sq ft. New construction still available with builder incentives.`,
    highlights: [
      "Del Webb 55+ community",
      "Strip & valley panoramas",
      "Resort amenity center",
      "Pickleball & bocce",
      "Single-story plans",
      "New construction available",
    ],
    bestFor: [
      "55+ active adult buyers",
      "Downsizers from CA & WA",
      "Lock-and-leave lifestyle",
      "Views-priority buyers",
    ],
    address: "Heritage Hills Ave",
    zip: "89138",
  },
  {
    slug: "the-vistas",
    name: "The Vistas",
    tagline: "Established luxury with mountain and valley views",
    priceRange: "$650K – $2M",
    description: `The Vistas is one of Summerlin West's established luxury villages, known for wide streets, mature landscaping, and some of the best valley and mountain views in the corridor. Guard-gated neighborhoods sit alongside non-gated custom sections. Homes range from 2,500-square-foot resales to sprawling custom estates on cul-de-sac lots. The Vistas is fully built out, meaning buyers get established neighborhoods with no construction traffic — a premium for many relocating executives and empty-nesters.`,
    highlights: [
      "Established community",
      "Guard-gated options",
      "Mountain & valley views",
      "Custom estate lots",
      "Mature landscaping",
      "No active construction",
    ],
    bestFor: ["Luxury resale buyers", "Privacy seekers", "Move-up buyers", "Executives relocating"],
    address: "The Vistas",
    zip: "89138",
  },
  {
    slug: "skye-canyon",
    name: "Skye Canyon",
    tagline: "Northwest Las Vegas's fastest-growing master plan",
    priceRange: "$450K – $1.2M",
    description: `Skye Canyon is northwest Las Vegas's most vibrant new master-planned community — a walkable, park-centered development anchored by Skye Center, a 9,000-square-foot amenity hub with resort pools, fitness, a community garden, and year-round programming. Builders including Lennar, KB Home, and Pulte are still delivering new phases, meaning buyers can lock in builder incentives and customize finishes. Easy access to US-95 and the 215 Beltway. Outdoor recreation at Sheep Mountain and the Sheep Range is minutes away.`,
    highlights: [
      "Skye Center amenity hub",
      "Resort pools & fitness",
      "New construction available",
      "Multiple top builders",
      "US-95 & 215 access",
      "Mountain recreation nearby",
    ],
    bestFor: ["New construction buyers", "First-time luxury buyers", "Families", "CA equity buyers"],
    address: "Skye Canyon Park Dr",
    zip: "89166",
  },
];

export function getSummerlinCommunity(slug: string): MarketCommunity | undefined {
  return summerlinCommunities.find((c) => c.slug === slug);
}
